### ISSUE TITLE
Make icon transparent

### ISSUE THREAD

**Issue by licaon-kter** [gabm/TapAndTurn#1]
Or better said, more transparent, now it's kinda a dark gray somewhat transparent square, on my Xperia 5.1.1

**Comment by gabm** [comment]
well for me it is and it's supposed to be... I'll check on a 5.1 phone

**Comment by licaon-kter** [comment]
How I see it: https://i.imgur.com/D9MKTy7.jpg

**Comment by gabm** [comment]
aaah well that's how it was supposed to be.. as i see it is transparent, but with a dark gray overlay for enhanced contrast with the white (and opaque) logo..


how would you expect it to be? maybe we can make it more configurable...

**Comment by licaon-kter** [comment]
It's ugly :(, I'd rather have it high contrast, say only the white current part (but a certain configurable colour) with some sort of shadow, but no background, all transparent. I'll try a mockup soon.

**Comment by gabm** [comment]
perfect! 

to achieve some contrast it would also be possible to have a border around the icon... 

just took this one from material design icons of Google because of it's expressiveness and it's license, but if you're skilled (I'm certainly not) you can also take a shot..



On 4 December 2016 20:59:41 CET, licaon-kter <notifications@github.com> wrote:
>It's ugly :(, I'd rather have it high contrast, say only the white
>current part (but a certain configurable colour) with some sort of
>shadow, but no background, all transparent. I'll try a mockup soon.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabm/TapAndTurn/issues/1#issuecomment-264726822

--
M.Sc. Matthias Gabriel
Fakultät für Elektrotechnik und Informationstechnik

Technische Universität Chemnitz
Reichenhainer Straße 70 | R. W440
09126 Chemnitz
Germany

Tel: +49 371 531-34458
Fax: +49 371 531-834458 

matthias.gabriel@etit.tu-chemnitz.de www.tu-chemnitz.de

**Comment by licaon-kter** [comment]
Does this look ok: https://i.imgur.com/UNZRYh5.jpg ?

Unfortunately they're [just outlined in GIMP](https://graphicdesign.stackexchange.com/questions/696/make-an-outline-with-gimp-like-in-photoshop), would that just work? Say I treat all sizes with this and that's it?

**Comment by gabm** [comment]
maybe it would be better to use the vector drawable, modify it (for example using inkscape). This way we could also add accents programmatically to shade the icon in different colors...  svgs and pngs are located here: https://github.com/google/material-design-icons

otherwise we can also use the pngs, guess it's less work ;)

**Comment by gabm** [comment]
oh i see that importing svg directly doesn't work... anyway: svg would be the better way to go as you can render all necessary sizes of pngs out of it...

**Comment by licaon-kter** [comment]
I agree, I'll need to look up how that is done though (outline the SVGs). :)

**Comment by licaon-kter** [comment]
offtopic: @gabm Thank you for the invitation, I declined it since I'm not really able to add more here, in terms of coding. :)

**Comment by gabm** [comment]
@licaon-kter it's not important - but you're very active here and contributed already ... code is not important

**Comment by gabm** [comment]
I took a new shot: https://streamable.com/s/ns7m0/ihfkit

what do you think?

(its about the symbol itself.. the rotation animation is a bit messed up because of the video recording)

**Comment by licaon-kter** [comment]
Looks nice.

**Comment by jpggithub** [comment]
I dowloaded the last version of tap'n'turn (2.4.0). It would be nice if we could choose between different basic colors and different animation. The previous animation was more explicit from my point of view.
Anyway, many thanks for this useful app! :-)

**Comment by licaon-kter** [comment]
There was no "previous" animation, back then it was only an icon.
Albeit I do agree that the orange colour does not popup that much, I don't see it most of the time.
Not sure what colour would be better though.

Ideas?

**Comment by gabm** [comment]
Well I'm not sure, whether just a change of colour would help.. actually one design goal was to make it less imminent: when you *actually* want to rotate, then you know where and what to look for... but if the rotation is not intended, then you don't want it's appearance to distract you..

That being said, you have a problem of contrasts though... this orange on black background works well but on other colors it doesn't. I tried to improve the situation using a shadow, that can provide additional contrast, specially on white...

actually there are a lot of parameters: shape, size, time, animation, color and so on.. please contribute your suggestions, play with mockups and so on.. I'm more than happy to merge your input!
