### ISSUE TITLE
INSTALL button blocked

### ISSUE THREAD

**Issue by H2172** [gabm/TapAndTurn#21]
When the TnT service is running, it blocks the INSTALL button when trying to install other apps/apk

**Comment by gabm** [comment]
yes that's a known limitation by android. As TnT uses an overlay to force a certain orientation, but when overlays are present then android blocks clicks to restricted buttons (like install button)

In the latest version 2.2.0 the problem is solved by not adding an overlay in the default orientation (portrait on phones). So in this orientation you can click the buttons. Anyway, what always works is simply turning off TnT for these moments. There is no proper workaround...

**Comment by H2172** [comment]
I have 2.2.0, let me try a few more times if the default orientation does the trick

**Comment by gabm** [comment]
the notification should also tell you, whether an overlay is added or not...

The recognition for the default orientation is somewhat hacky because there is no proper way of querying it, so it's assumed that you hold your phone upright when you start the service

**Comment by H2172** [comment]
OK confirmed; perhaps my phone happened to be in landscape last time I booted
