### ISSUE TITLE
Can't install apps if enabled

### ISSUE THREAD

**Issue by gkaklas** [gabm/TapAndTurn#27]
When Tap 'n' Turn is running and I try to install an apk, I can only press the "Cancel" button but not "Install". This doesn't happen every time and happens even when no icon is displayed. I guess that, for security reasons, Android doesn't allow me to install apps when there is an overlay?

If I disable Tap 'n' Turn and return to the installer's activity I can install an apk without any problems.

**Comment by licaon-kter** [comment]
/close this as duplicate of #10

This and #17 forced me to install it. :-(

**Comment by gkaklas** [comment]
Sorry, I checked the other open issues and didn't see it

**Comment by gkaklas** [comment]
Reopened, I just found some time to read the comments in #10 which suggest to install version 2.1.1.

I'm running the latest version, 2.2.0, and still have this issue (I'm using CM13).

**Comment by licaon-kter** [comment]
Actually #10 should be reopened, but it does not matter, the issue is still alive. :)

**Comment by haarp** [comment]
I can confirm it. It interacts well with installation dialogs most of the time, but at some point it starts blocking them. Quickly disabling and re-enabling the service solves this for a while, but the problem will be back.

**Comment by gabm** [comment]
I plan to release a new version soon where this problem should be tackled.. Maybe you can give me some feedback on the new strategy...

## Problem
The problem was, that I wanted the user to lock it's device into a certain orientation using the built-in orientation mechanism. Only when the device gets forced out of this orientation via a button press, i added an overlay and thus removing the possibility to use restricted buttons. The crucial part it's somehow to detect, whether we are in this "default orientation" and we therefore can remove the overlay or not. Somehow it got messed up and that's why your issue came up...


## Proposed solution
I implemented a completely manual way that is more transparent and i plan to release it soon: We always add an overlay and therefore never can use restricted buttons. Like this it never gets messed up and does properly do it's job. Further we can use it with automatic rotation of android enabled and disabled, which does allow reverse portrait on my phone. If the user wants to use restricted buttons, he can manually disable TnT via the notification and disable after he pressed "Install"

What do you guys think? it should work much more stable ..

**Comment by licaon-kter** [comment]
Other apps like CF.lumen trigger correctly.

The notification is annoying and useless 99% of the time, while I understand it's needed, I will hide it...

**Comment by gabm** [comment]
what does cf lumen to? does it detect systemapps automatically or how does it solve this problem?

**Comment by haarp** [comment]
Agreed with @licaon-kter. It would also be annoying having to disable/enabled TnT every time I want to install something. I would not be using it if that was necessary.

**Comment by gabm** [comment]
ok guys.. shame on me :/ got it ^^ 

-> so apparently its not the pure presence that decides whether you can press these buttons but whether the overlay is over the restricted button or not - I assumed it was the presence of an overlay that disallows pressing this button ... So I found the solution: just resize the overlay to 0px, so it doesnt cover anything... So now we can have the overlay added while being able to press the buttons... :)

**Comment by gabm** [comment]
This should be fixed in v2.3.0 which will be released to F-Droid in some days...

**Comment by gabm** [comment]
please check back, v2.3.0 got released today!

**Comment by gkaklas** [comment]
This probably needs to be reopened 😟 . With the new update there is no problem when installing apps, but I get the same error when an application asks for a permission, after clicking "Allow" on the popup that asks me to give the permission.

I would open a new issue but it seems like a similar situation.

**Comment by gabm** [comment]
Which version are you using? 2.6.0?

How does it relate to #38?

**Comment by licaon-kter** [comment]
It's #38 ;)

**Comment by gabm** [comment]
I'm surprised it came up now?! must have been a problem earlier, no?

**Comment by licaon-kter** [comment]
It's an Android >= 6 issue, and I was on 5.1.1 mostly.
Also, if you don't install or setup new apps you might not see it.

And don't forget this: https://developer.android.com/about/dashboards/index.html#Platform

**Comment by gabm** [comment]
but I'm on 7.1.2 and there it doesn't seem to exist?!

**Comment by licaon-kter** [comment]
Maybe they changed that, so you and other 1% don't have this. ;)

**Comment by gabm** [comment]
strange stuff indeed :/

I just tried to implement your suggestion from #38 but it seems the mentioned action doesnt exist!? Its clearly in the source code but not in SDK 25 (yet?).. your proposed solution doesnt seem to work :/

**Comment by licaon-kter** [comment]
Says Android M so SDK23? No idea really, just got that by searching around.

/LE: Make sense to not have it in SDK25 if you don't see this issue, I guess

**Comment by gabm** [comment]
yes, I checked with SDK 25 and there I couldn't find that?! ...

**Comment by gkaklas** [comment]
Sorry guys, it is #38, I didn't see it. It's been a problem for a few months (I can't remember which version though, probably even after 2.3.0) but I'm not asked very often to give permissions so it seemed random at first and took a while until I was able to reproduce it.

Unfortunately I don't have the Android experience to make a code-wise suggestion 😕.  But I think that this can be closed, and that the conversation seems more relevant in #38 🤔 (I also subscribed so maybe I can test it if it gets fixed). I should probably also note that I still have this issue after the last update, 2.7.0.
